package com.may.xiaomi.dao;

import com.may.xiaomi.entry.GoodsImages;
import com.may.xiaomi.entry.GoodsImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    long countByExample(GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    int deleteByExample(GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    int insert(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    int insertSelective(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    List<GoodsImages> selectByExample(GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    GoodsImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") GoodsImages record, @Param("example") GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    int updateByExample(@Param("record") GoodsImages record, @Param("example") GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    int updateByPrimaryKeySelective(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Thu Aug 26 15:59:32 CST 2021
     */
    int updateByPrimaryKey(GoodsImages record);
}